# Generated by Django 3.2.7 on 2021-09-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
