# Generated by Django 3.2.7 on 2021-09-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
