# Generated by Django 3.2.7 on 2021-09-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
